<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2016/9/7
 * Time: 11:21
 */

namespace app\modules\admin\models;
use yii\db\ActiveRecord;

class CategoryForm extends ActiveRecord
{
/*    public $title;
    public $intra;
    public $order_num;*/
    public function rules()
    {
     //   return parent::rules(); // TODO: Change the autogenerated stub
        return [
            [['title','intra','order_num'],'required','message'=>'不能为空'],
            ['order_num','number']
        ];
    }
    public static function tableName()
    {
        return 'w_category';
     //   return parent::tableName(); // TODO: Change the autogenerated stub
    }
}