<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2016/9/6
 * Time: 11:47
 */

namespace app\modules\admin\models;
use Yii;
use yii\base\Model;
use yii\db\ActiveRecord;

class user extends ActiveRecord
{
   public $usernname;
    public $password;
    public $lever;
    /*   public function rules()
      {
        //  return parent::rules(); // TODO: Change the autogenerated stub
          return [
              [['username','password','lever'],'required'],
          ];
      }
      public static  function tableName()
      {
          return 'user';
       //   return parent::tableName(); // TODO: Change the autogenerated stub
      }*/
}