<?php return array (
  'email_type' => '1',
  'email_safe' => '',
  'mail_address' => '',
  'smtp' => '',
  'smtp_user' => '',
  'smtp_pwd' => '',
  'smtp_port' => '',
  'order_by' => 'new',
  'order_type' => 'asc',
  'list_type' => 'win',
  'auto_finish' => '1',
  'index_slide' => 'a:2:{i:0;a:3:{s:4:"name";s:6:"山城";s:3:"url";s:1:"/";s:3:"img";s:39:"upload/2015/08/03/20150803024648883.jpg";}i:1;a:3:{s:4:"name";s:7:"山城2";s:3:"url";s:1:"/";s:3:"img";s:39:"upload/2015/08/04/20150804040528454.jpg";}}',
  'name' => '山城速购',
  'url' => '',
  'master' => '',
  'qq' => '',
  'email' => '',
  'mobile' => '',
  'phone' => '',
  'address' => '',
  'site_footer_code' => '<div class=\\"footer\\" style=\\"text-align:center;\\">	<p class=\\"links\\">		<a href=\\"http://www.baidu.com\\" target=\\"_blank\\">关于我们</a>|<a href=\\"\\">常见问题</a>|<a href=\\"\\">安全交易</a>|<a href=\\"\\">购买流程</a>|<a href=\\"\\">如何付款</a>|<a href=\\"\\">联系我们</a>|<a href=\\"\\">合作提案</a> 	</p>	<p class=\\"copyright\\">		Powered by <a href=\\"http://\\">耐耐云商</a> 	</p>Copyright © 2005-2014 <a class=\\"copyys\\" target=\\"_blank\\" href=\\"http://www.miibeian.gov.cn/\\">鲁ICP备01000010号</a></div>',
  'tax' => '10',
  'stockup_time' => '1',
  'index_seo_title' => '山城第一电商',
  'index_seo_keywords' => '山城速购',
  'index_seo_description' => '山城速购',
  'goods_no_pre' => 'SD',
  'service_online' => 'a:1:{i:0;a:2:{s:4:"name";s:0:"";s:2:"qq";s:0:"";}}',
)?>