<?php return array (
  'email_type' => '1',
  'email_safe' => '',
  'mail_address' => '',
  'smtp' => '',
  'smtp_user' => '',
  'smtp_pwd' => '',
  'smtp_port' => '',
  'order_by' => 'new',
  'order_type' => 'asc',
  'list_type' => 'win',
  'auto_finish' => '1',
  'index_slide' => 'a:3:{i:0;a:3:{s:4:"name";s:33:"新设计，新内核，新起点";s:3:"url";s:20:"http://www.jooyea.cn";s:3:"img";s:39:"upload/2015/07/18/20150718020448553.jpg";}i:1;a:3:{s:4:"name";s:18:"开源电子商务";s:3:"url";s:20:"http://www.jooyea.cn";s:3:"img";s:39:"upload/2015/07/18/20150718020448566.jpg";}i:2;a:3:{s:4:"name";s:9:"大减价";s:3:"url";s:20:"http://www.jooyea.cn";s:3:"img";s:39:"upload/2015/07/18/20150718023925254.jpg";}}',
  'name' => 'iWebShop开源电子商务平台',
  'url' => 'http://www.aircheng.com',
  'master' => '',
  'qq' => '',
  'email' => '',
  'mobile' => '',
  'phone' => '',
  'address' => '',
  'site_footer_code' => '<div class=\\"footer\\" style=\\"text-align:center;\\">	<p class=\\"links\\">		<a href=\\"http://www.baidu.com\\" target=\\"_blank\\">关于我们</a>|<a href=\\"\\">常见问题</a>|<a href=\\"\\">安全交易</a>|<a href=\\"\\">购买流程</a>|<a href=\\"\\">如何付款</a>|<a href=\\"\\">联系我们</a>|<a href=\\"\\">合作提案</a> 	</p>	<p class=\\"copyright\\">		Powered by <a href=\\"http://www.aircheng.com\\">iWebShop</a> 	</p>Copyright © 2005-2014 <a class=\\"copyys\\" target=\\"_blank\\" href=\\"http://www.miibeian.gov.cn/\\">鲁ICP备01000010号</a></div>',
  'tax' => '10',
  'stockup_time' => '1',
  'index_seo_title' => 'iWebShop开源商城系统',
  'index_seo_keywords' => '开源商城系统,开源网店系统,开源电子商务,商城系统源码,多用户商城源码',
  'index_seo_description' => 'iwebshop是基于php开发b2c2c开源多用户商城系统,支持商家入驻,支持微商城,手机移动商城,APP商城多为一体的电子商务系统',
  'goods_no_pre' => 'SD',
  'service_online' => 'a:1:{i:0;a:2:{s:4:"name";s:0:"";s:2:"qq";s:0:"";}}',
)?>